### PR TITLE
Removes imperative focus in App.js and starts on flattening the setState call chains.

### PR DESCRIPTION
**Pull request by evgenyfadeev**
In this PR App.js stops finding element by id "your-typed-text".

Instead there is a new integer state variable that is used in an effect of TypedText component to focus.

Also it starts flattening the setState() call chains, but adding a parameter to `setupLesson` method.

If this method is reasonable, I can remove the remaining setState chains.

All tests are passing and the auto-focus seems to work.

### CODE REVIEW

**Comment by evgenyfadeev** [comment]
It may be ok actually, I had an issue with a revision lesson in a different experiment (branch evgenyfadeev:app-js-remove-imperative-focus-flatten-setstate-2)

**Comment by didoesdigital** [comment]
@evgenyfadeev I'm excited about the direction to flatten the set state call chains! However, it seems like there are some sneaky scenarios where it does not behave correctly. I guess `setupLesson()` still needs to be called later after certain bits of code are run (but I'm not sure exactly which bits or where).

Here are some scenarios to test:

- Upon first visit to the [Numbers lesson with "Limit word count" set to 2, "Start from word" set to 2, "Repetitions" set to 2, and Sort set to "Lesson default"](http://localhost:3000/typey-type/lessons/fundamentals/numbers/?limitNumberOfWords=2&startFromWord=2&repetitions=2&sortOrder=sortOff), it should show the Material `1​ 2 1 2`. On this PR's branch, it shows me `0` initially until I change a User Setting or press Restart or some other action that calls `setupLesson()` again.
- When "New words" is checked and "Seen words"/"Memorised words" are unchecked (i.e. the Preset is set to "Discover") and `metWords` includes lots of words, navigating to the "Next lesson" (from the Finished lesson screen) should see that the next lesson only contains seen/memorised words and show `There are no words to write.` and a "Next lesson" button. On this PR's branch, when navigating to the Next lesson, it fails to recognise that the first word of the next lesson has already been seen and shows that 1 word instead of the `There are no words to write.` screen.

While testing the flattened set state call chain, I noticed different results compared to `master` when logging `newPresentedMaterial` around `// Reset lesson state for starting lesson` and the `render` of `App.js`. Unrelated to this PR, it looks like the `master` branch already had some bugs around setting `newPresentedMaterial` using a `new Zipper()`. The Zipper is supposed to take an array and return an object with a `current` field that is 1 `MaterialItem` (an object with `phrase` and `stroke`). In some cases, Typey Type is incorrectly calling `new Zipper()` with an existing array variable wrapped in a new array and in some cases the `newPresentedMaterial.current` value is an array or undefined. I think the fix is to remove the `[]` from these 3 lines:

https://github.com/didoesdigital/typey-type/blob/55bb930e3541d30347574e6e214331bc5be07d8d/src/App.js#L320

https://github.com/didoesdigital/typey-type/blob/55bb930e3541d30347574e6e214331bc5be07d8d/src/App.js#L486

https://github.com/didoesdigital/typey-type/blob/55bb930e3541d30347574e6e214331bc5be07d8d/src/utils/typey-type.js#L357

You can either add those fixes as part of this work or we could do them on a separate PR, up to you.

**Comment by didoesdigital** [comment]
Regarding the focus changes, here are all the scenarios I tested:

- Scenarios where we should return focus to Typed Text field:
    - [x] on Custom Lesson Setup, clicking "Start custom lesson" should return focus to Typed Text field
    - [x] on Lessons index page, clicking "Start custom lesson" should return focus to Typed Text field
    - [x] double-clicking "Say word" button should return focus to Typed Text field
    - [x] clicking lesson "Restart" button should return focus to Typed Text field
    - [x] clicking Finished screen "Restart lesson" button should return focus to Typed Text field
    - [x] clicking Finished screen "Next lesson" button should return focus to Typed Text field
    - [x] clicking Finished screen "Revise these words" link button should return focus to Typed Text field
    - [x] clicking Lesson "Revision mode ×" link button should return focus to Typed Text field
    - [x] clicking empty lesson "Start from word 1" button should return focus to Typed Text field
    - [x] starting a lesson from the Lesson index page, Progress page recommendations Progress page lesson list, and Progress page links to "progress lessons" from "Practice all words", "Drill X memorised words", and "Revise Y seen words", and the extra "Discover new words" link should all start with focus on Typed Text
    - [x] pressing "Shift+Enter" while on Typed Text should keep focus on Typed Text field
    - [x] clicking the stroke hint link should return focus to Typed Text field
    - [x] changing User Settings on the Finished screen specifically should re-set up the lesson and should return focus to Typed Text field
- Scenarios where we should NOT return focus to Typed Text field:
    - [x] changing User Settings on the Main Lesson View screen should NOT return focus to Typed Text field
    - [x] pressing the Metronome buttons, Show/Hide Settings buttons, and Show/Hide Scores controls should NOT return focus to Typed Text field
    - [x] clicking the "Skip to main content" should jump to the lesson Heading and should NOT return focus to Typed Text field
- Scenarios around main headings:
    - [x] navigating to each page focuses on the main heading so if you then hit Tab it will focus the next item after the heading e.g. clicking "Writer" in the primary nav then "Tab" will focus "Download diagram (SVG)"
    - [x] using a pointer/mouse interaction to navigate to each page should focus on the main heading WITHOUT a visible focus style
    - [x] using keyboard interaction like Enter to navigate to pages should highlight the heading with a visible focus style
    - [x] using keyboard interaction like Tab then pressing the browser back button should highlight the heading with a visible focus style
    - [x] at the end of the Break timer it should move focus to new the `Your break is done` heading on page
- Other:
    - [ ] navigating "Back to lesson" from Overview or Flashcards could probably return focus to Typed Text field or the main lesson heading

For the last scenario, Typey Type previously returned the focus to the lesson heading and on this PR returns focus to Typed Text field. I don't have strong feelings here, either behaviour is fine.

**Comment by evgenyfadeev** [comment]
Thanks for the feedback @didoesdigital , I'll make another round in the coming weekend.

**Comment by evgenyfadeev** [comment]
@didoesdigital seems that indeed the issue was with the Zipper use. I cannot reproduce the focus loss in one scenario "navigating "Back to lesson" from Overview or Flashcards could probably return focus to Typed Text field or the main lesson heading"...

**Comment by didoesdigital** [comment]
That's fine @evgenyfadeev, not too worried about that one

**Comment by evgenyfadeev** [comment]
Are you going to merge this PR first or I should continue with removing the remaining setState callbacks? Do you think this needs more testing @didoesdigital ? I have some time for this tomorrow (Nov 18th).

**Comment by didoesdigital** [comment]
@evgenyfadeev with the latest changes on this PR, I still see issues with these 2 scenarios:

- Upon first visit to the [Numbers lesson with "Limit word count" set to 2, "Start from word" set to 2, "Repetitions" set to 2, and Sort set to "Lesson default"](http://localhost:3000/typey-type/lessons/fundamentals/numbers/?limitNumberOfWords=2&startFromWord=2&repetitions=2&sortOrder=sortOff), it should show the Material `1​ 2 1 2`. On this PR's branch, it shows me `0` initially until I change a User Setting or press Restart or some other action that calls `setupLesson()` again.
- When "New words" is checked and "Seen words"/"Memorised words" are unchecked (i.e. the Preset is set to "Discover") and `metWords` includes lots of words, navigating to the "Next lesson" (from the Finished lesson screen) should see that the next lesson only contains seen/memorised words and show `There are no words to write.` and a "Next lesson" button. On this PR's branch, when navigating to the Next lesson, it fails to recognise that the first word of the next lesson has already been seen and shows that 1 word instead of the `There are no words to write.` screen.

Once those scenarios are working, then I can merge the PR.

For the first scenario, here's what I saw when I visited <http://localhost:3000/typey-type/lessons/fundamentals/numbers/?limitNumberOfWords=2&startFromWord=2&repetitions=2&sortOrder=sortOff>:

incorrect material on Numbers lesson showing all of the numbers

On first load, the material does not match the settings like it should. Then, when I increased the "Limit word count" to 3, it ran `setupLesson` again and fixed the material to match the settings:

correct material on Numbers lesson showing only 1 2 3 1 2 3

The material needs to be match the settings from the start.

**Comment by evgenyfadeev** [comment]
@didoesdigital it seems that I've fixed this behaviour - the first scenario is resolved, I'm not sure exactly how to test the second one, but I think it should be fixed as well.

The issue was that I was applying the state patch to the setupLesson in the end of the function, so that some of the code in this function had no effect.

This latest commit applies the patch in the beginning of the function, more closely simulating the chain of setState calls.

**Comment by didoesdigital** [comment]
@evgenyfadeev I've reviewed your latest change and it fixes the 2 previous scenarios (first visit of Numbers lesson with limited material and next lesson properly checking seen words filter).

I noticed another issue with revision mode. I had a go at fixing that issue, which you can see in this commit on a branch I made to check out your code: https://github.com/didoesdigital/typey-type/commit/ff7faae7ad40c5e938b8f2c7e25275bba9254ca1

Have a look at that link's commit message to see the revision mode scenarios that were misbehaving. Note that the commit also includes some commented lines where I *think* we might need to set `revisionMode` later on when we flatten other set state chains.

I *think* with that commit's addition, this chunk of work will be ready to merge. It's late in the day so I'll wait until another day to do more testing and merge and deploy, but this is looking promising!

Thanks so much for all of your work on this! And your patience since I haven't been able to review the latest code until now 🙏

**Comment by didoesdigital** [comment]
@evgenyfadeev for future branches removing the remaining setState callbacks, I will likely do thorough testing around the following:

- Progress lessons like [Practice your words](http://localhost:3000/typey-type/lessons/progress/). [Drill X memorised words](http://localhost:3000/typey-type/lessons/progress/memorised/). [Revise Y seen words](http://localhost:3000/typey-type/lessons/progress/seen/). [Discover new words](http://localhost:3000/typey-type/lessons/drills/top-10000-project-gutenberg-words/?recommended=true&study=discover&showStrokes=1&hideStrokesOnLastRepetition=1&newWords=1&seenWords=0&retainedWords=0&repetitions=5&limitNumberOfWords=15&sortOrder=sortOff).
- Custom lessons made from the setup page: http://localhost:3000/typey-type/lessons/custom/setup
- Generated lessons: http://localhost:3000/typey-type/lessons/custom/generator
- Revision mode accessed by the "Revise these words" link at the end of a lesson
- Lessons from each category (fundamentals, drills, stories, collections)
- Stop/restart lesson buttons in the lesson header, and "Next lesson" link at the end of a lesson
- Navigating to/from lesson Overview and Flashcard pages
- All the user settings, particularly the ones that affect the content of the lesson material like Limit word count, Memorised words, Simple typography, and so on

I don't expect you or anyone contributing to Typey Type to test _all_ of the many hidden magic behaviours of Typey Type. Just figured I'd note these to give you an idea of the areas I might check myself relating to `App.js` lesson code.

**Comment by evgenyfadeev** [comment]
Hi @didoesdigital  I'll try to test what I can according to this list in the future PR, however I might be unable to understand what is expected from the app in detail, so you'll probably need to re-test anyway. In fact at first mistook the "no more words in the exercise" for a bug, but in fact it was desired behavior - that's why my initial PR had the issue.

It is possible that new bugs will surface once all setState are "unchained", because the chaining triggers re-renders which in turn might trigger state updates. Still, it's probably worthwhile to follow through with this refactoring because it is probably simpler than a rewrite.

**Comment by didoesdigital** [comment]
Hi @evgenyfadeev, I've merged this PR and deployed it to production! 🥳 Thanks so very much for your work on this! It's a messy part of the app and I'm very grateful.  

> Hi @didoesdigital, thank you for rewviewing this. I'll try to test what I can according to this list in the future PR and keep ind mind your comment regarding the revisionLesson, however I might be unable to understand what is expected from the app in detail, so you'll probably need to re-test anyway.

That makes sense, and I'm happy to re-test 👍

> In fact at first mistook the "no more words in the exercise" for a bug, but in fact it was desired behavior - that's why my initial PR had the issue.

Hah, that's not one I would have thought of, good to know!

> It is possible that new bugs will surface once all setState are "unchained", because the chaining triggers re-renders which in turn might trigger state updates. Still, it's probably worthwhile to follow through with this refactoring because it is probably simpler than a rewrite.

Yes, I like the direction of this kind of flattening refactoring. We should be able to get a few stable releases done in this fashion without too many new bugs but it's possible some will sneak through and continuing to follow through with this refactoring approach until `App.js` is cleaned up will make it easier to fix them.

**Pull request merged**
